/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author aurelia
 */
public class ControladorQytetet extends javax.swing.JFrame {
    private modeloqytetet.Qytetet modeloQytetet;

    /**
     * Creates new form ControladorQytetet
     */
    public ControladorQytetet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SalirCarcelDado = new javax.swing.JButton();
        SalirCarcelPagando = new javax.swing.JButton();
        Jugar = new javax.swing.JButton();
        AplicarSorpresa = new javax.swing.JButton();
        SiguienteTurno = new javax.swing.JButton();
        ComprarPropiedad = new javax.swing.JButton();
        EdificarCasa = new javax.swing.JButton();
        EdificarHotel = new javax.swing.JButton();
        VenderPropiedad = new javax.swing.JButton();
        HipotecarPropiedad = new javax.swing.JButton();
        CancelarHipoteca = new javax.swing.JButton();
        vistaQytetet1 = new GUIQytetet.VistaQytetet();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SalirCarcelDado.setText("Salir Cárcel Dado");
        SalirCarcelDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirCarcelDadoActionPerformed(evt);
            }
        });

        SalirCarcelPagando.setText("Salir Cárcel Pagando");
        SalirCarcelPagando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirCarcelPagandoActionPerformed(evt);
            }
        });

        Jugar.setText("Jugar");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });

        AplicarSorpresa.setText("Aplicar Sorpresa");
        AplicarSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarSorpresaActionPerformed(evt);
            }
        });

        SiguienteTurno.setText("Siguiente turno");
        SiguienteTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteTurnoActionPerformed(evt);
            }
        });

        ComprarPropiedad.setText("Comprar propiedad");
        ComprarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarPropiedadActionPerformed(evt);
            }
        });

        EdificarCasa.setText("Edificar Casa");
        EdificarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdificarCasaActionPerformed(evt);
            }
        });

        EdificarHotel.setText("Edificar Hotel");
        EdificarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdificarHotelActionPerformed(evt);
            }
        });

        VenderPropiedad.setText("Vender Propiedad");
        VenderPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderPropiedadActionPerformed(evt);
            }
        });

        HipotecarPropiedad.setText("Hipotecar Propiedad");
        HipotecarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HipotecarPropiedadActionPerformed(evt);
            }
        });

        CancelarHipoteca.setText("Cancelar Hipoteca");
        CancelarHipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarHipotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComprarPropiedad)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(AplicarSorpresa))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(259, 259, 259))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SiguienteTurno)
                                .addGap(82, 82, 82)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CancelarHipoteca)
                            .addComponent(EdificarHotel)
                            .addComponent(EdificarCasa)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VenderPropiedad)
                                    .addComponent(HipotecarPropiedad))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SalirCarcelPagando)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(SalirCarcelDado)
                                        .addGap(8, 8, 8))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vistaQytetet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1874, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaQytetet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(AplicarSorpresa)
                        .addGap(19, 19, 19)
                        .addComponent(ComprarPropiedad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EdificarCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EdificarHotel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VenderPropiedad)
                                    .addComponent(SiguienteTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HipotecarPropiedad))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(SalirCarcelDado)
                                .addGap(15, 15, 15)
                                .addComponent(SalirCarcelPagando)))
                        .addGap(21, 21, 21)
                        .addComponent(CancelarHipoteca)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirCarcelDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirCarcelDadoActionPerformed
        boolean resultado = modeloQytetet.intentarSalirCarcel(modeloqytetet.MetodoSalirCarcel.TIRANDODADO);
        this.SalirCarcelPagando.setEnabled(false);
        this.SalirCarcelDado.setEnabled(false);
        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.Jugar.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this, "NO sales de la cárcel");
            this.SiguienteTurno.setEnabled(true);
        }
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_SalirCarcelDadoActionPerformed

    private void SalirCarcelPagandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirCarcelPagandoActionPerformed
        boolean resultado = modeloQytetet.intentarSalirCarcel(modeloqytetet.MetodoSalirCarcel.PAGANDOLIBERTAD);
        this.SalirCarcelPagando.setEnabled(false);
        this.SalirCarcelDado.setEnabled(false);
        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.Jugar.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this, "NO sales de la cárcel");
            this.SiguienteTurno.setEnabled(true);
        }
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_SalirCarcelPagandoActionPerformed

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        boolean bancarrota = modeloQytetet.getJugadorActual().getSaldo() <= 0;
        boolean tienePropietario;
        if (!bancarrota){
            tienePropietario = modeloQytetet.jugar(); 
            this.Jugar.setEnabled(false);
            if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == modeloqytetet.TipoCasilla.IMPUESTO)
                JOptionPane.showMessageDialog(this, "Te ha tocado pagar un impuesto");
            else if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == modeloqytetet.TipoCasilla.JUEZ){
                JOptionPane.showMessageDialog(this, "Tu juicio ha ido mal y te han mandado a prisión de nuevo\n Tu última opción es tener una carta de libertad o ser especulador y pagar una fianza");
            }  
            this.vistaQytetet1.actualizar(modeloQytetet);
            eleccionSegunCasilla(modeloQytetet.getJugadorActual().getCasillaActual().getTipo(),tienePropietario);
            bancarrota = modeloQytetet.getJugadorActual().getSaldo() <= 0;
        }
            
        if (!bancarrota){
            this.SiguienteTurno.setEnabled(true);
        }else
            finJuego();
        
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_JugarActionPerformed

    private void SiguienteTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteTurnoActionPerformed
        modeloQytetet.siguienteJugador();
        this.SiguienteTurno.setEnabled(false);
        this.actualizar(modeloQytetet);
    }//GEN-LAST:event_SiguienteTurnoActionPerformed

    private void ComprarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarPropiedadActionPerformed
        if(modeloQytetet.comprarTituloPropiedad()){
            JOptionPane.showMessageDialog(this,"Se ha realizado la compra");
        }else
            JOptionPane.showMessageDialog(this,"No se ha podido comprar");
        
        this.ComprarPropiedad.setEnabled(false);
        this.vistaQytetet1.actualizar(modeloQytetet);
        gestionInmobiliaria();
    }//GEN-LAST:event_ComprarPropiedadActionPerformed

    private void AplicarSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarSorpresaActionPerformed
        boolean tienePropietario = modeloQytetet.aplicarSorpresa();
        if (modeloQytetet.getCartaActual().getTipo() == modeloqytetet.TipoSorpresa.IRACASILLA && modeloQytetet.getCartaActual().getValor() == modeloQytetet.getTablero().getCarcel().getNumeroCasilla())
            JOptionPane.showMessageDialog(this, "Tu última opción es tener una carta de libertad o ser especulador y pagar una fianza");
        if (modeloQytetet.getJugadorActual().getSaldo()>0 && !modeloQytetet.getJugadorActual().getEncarcelado() && modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == modeloqytetet.TipoCasilla.CALLE){
            if(!tienePropietario){
                this.ComprarPropiedad.setEnabled(true);  
            }
        }
        this.AplicarSorpresa.setEnabled(false);
        this.vistaQytetet1.actualizar(modeloQytetet);
        // Una vez actualizado, si no está en la cárcel puede hacer gestiones
        gestionInmobiliaria();
    }//GEN-LAST:event_AplicarSorpresaActionPerformed

    private void EdificarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdificarCasaActionPerformed
        modeloqytetet.Calle c = (modeloqytetet.Calle) eleccionPropiedad(false);
        if(modeloQytetet.edificarCasa(c))
            JOptionPane.showMessageDialog(this,"Se ha edificado la casa");
        else
            JOptionPane.showMessageDialog(this,"No se ha podido edificar la casa");
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_EdificarCasaActionPerformed

    private void EdificarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdificarHotelActionPerformed
        modeloqytetet.Calle c = (modeloqytetet.Calle) eleccionPropiedad(false);
        if(modeloQytetet.edificarHotel(c))
            JOptionPane.showMessageDialog(this,"Se ha edificado el hotel");
        else
            JOptionPane.showMessageDialog(this,"No se ha podido edificar el hotel");
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_EdificarHotelActionPerformed

    private void VenderPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderPropiedadActionPerformed
        modeloqytetet.Calle c = (modeloqytetet.Calle) eleccionPropiedad(false);
        if(modeloQytetet.venderPropiedad(c))
            JOptionPane.showMessageDialog(this,"Se ha vendido la propiedad elegida");
        else
            JOptionPane.showMessageDialog(this,"No se ha podido vender la propiedad");
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_VenderPropiedadActionPerformed

    private void HipotecarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HipotecarPropiedadActionPerformed
        modeloqytetet.Calle c = (modeloqytetet.Calle) eleccionPropiedad(false);
        if(modeloQytetet.hipotecarPropiedad(c))
            JOptionPane.showMessageDialog(this,"Se ha hipotecado la propiedad");
        else
            JOptionPane.showMessageDialog(this,"No se ha podido hipotecar la propiedad");
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_HipotecarPropiedadActionPerformed

    private void CancelarHipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarHipotecaActionPerformed
        modeloqytetet.Calle c = (modeloqytetet.Calle) eleccionPropiedad(true);
        if(modeloQytetet.cancelarHipoteca(c))
            JOptionPane.showMessageDialog(this,"Se ha cancelado la hipoteca de la propiedad");
        else
            JOptionPane.showMessageDialog(this,"No se ha podido cancelar la hipoteca");
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_CancelarHipotecaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ControladorQytetet controladorQytetet= new ControladorQytetet();
        
        CapturaNombreJugadores capturaNombres = new CapturaNombreJugadores(controladorQytetet, true);
        ArrayList<String> nombres = capturaNombres.obtenerNombres();
        
        Dado.createInstance(controladorQytetet);
        modeloqytetet.Qytetet modelo = modeloqytetet.Qytetet.getInstance();
        modelo.inicializarJuego(nombres);
        
        controladorQytetet.actualizar(modelo);
        
        controladorQytetet.setVisible(true); 
        
    }
    
    private void finJuego(){
        if (modeloQytetet.getJugadorActual().getSaldo()<=0){
            JOptionPane.showMessageDialog(this, "El juego ha terminado \n El ranking es:\n" + modeloQytetet.obtenerRanking().toString());
        }
    }
    
    public void habilitarComenzarTurno(){
        this.EdificarCasa.setEnabled(false);  
        this.EdificarHotel.setEnabled(false);  
        this.VenderPropiedad.setEnabled(false);  
        this.HipotecarPropiedad.setEnabled(false);  
        this.CancelarHipoteca.setEnabled(false);  
        this.Jugar.setEnabled(false);
        this.SalirCarcelDado.setEnabled(false);
        this.SalirCarcelPagando.setEnabled(false);
        this.ComprarPropiedad.setEnabled(false);
        this.SiguienteTurno.setEnabled(false);
        this.AplicarSorpresa.setEnabled(false);
        if(modeloQytetet.getJugadorActual().getEncarcelado()){
            this.SalirCarcelPagando.setEnabled(true);
            this.SalirCarcelDado.setEnabled(true);
        }
        else
            this.Jugar.setEnabled(true);
    }
    
    private void eleccionSegunCasilla(modeloqytetet.TipoCasilla tipo, boolean tienePropietario){
        
        if (modeloQytetet.getJugadorActual().getSaldo()>0 && !modeloQytetet.getJugadorActual().getEncarcelado()){
            if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == modeloqytetet.TipoCasilla.CALLE){
                if(!tienePropietario){
                    this.ComprarPropiedad.setEnabled(true);  
                }else
                    JOptionPane.showMessageDialog(this, "Ups, has caído en una propiedad privada. Paga si no te pertenece");
  
            }else if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == modeloqytetet.TipoCasilla.SORPRESA){
                JOptionPane.showMessageDialog(this,"Se ha cogido una carta sorpresa");
                this.AplicarSorpresa.setEnabled(true);  
            }
        }
        gestionInmobiliaria();
        this.vistaQytetet1.actualizar(modeloQytetet);
    }
    
    private void gestionInmobiliaria(){
        if (!modeloQytetet.getJugadorActual().getEncarcelado() && modeloQytetet.getJugadorActual().getSaldo() > 0 && modeloQytetet.getJugadorActual().tengoPropiedades())
        {
            this.EdificarCasa.setEnabled(true);  
            this.EdificarHotel.setEnabled(true);  
            this.VenderPropiedad.setEnabled(true);  
            this.HipotecarPropiedad.setEnabled(true);  
            this.CancelarHipoteca.setEnabled(true);  
            //this.SiguienteTurno.setEnabled(true); //ver si quitar 
        }
        this.vistaQytetet1.actualizar(modeloQytetet);
    }
    
    private modeloqytetet.Casilla eleccionPropiedad(boolean opcion){
        ArrayList<modeloqytetet.Casilla> propiedades = modeloQytetet.propiedadesHipotecadasJugador(opcion);
        int tam = propiedades.size();
        String calles = "";
        for (int i = 0; i<tam; i++)
            calles += "Propiedad " + i + ":     " + ((modeloqytetet.Calle) propiedades.get(i)).getTitulo().getNombre() + ": Nº casas: " + ((modeloqytetet.Calle) propiedades.get(i)).getNumCasas() + " Nº hoteles: " + ((modeloqytetet.Calle) propiedades.get(i)).getNumHoteles() + "\n";
        int numero = Integer.parseInt(JOptionPane.showInputDialog("Introduce el número de la propiedad con la que deseas realizar la opción \n" + calles));
        
        modeloqytetet.Calle c = (modeloqytetet.Calle) propiedades.get(numero);
        return c;
    }
    
    public void actualizar(modeloqytetet.Qytetet qytetet){
        vistaQytetet1.actualizar(qytetet);
        this.modeloQytetet = qytetet;
        this.habilitarComenzarTurno();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AplicarSorpresa;
    private javax.swing.JButton CancelarHipoteca;
    private javax.swing.JButton ComprarPropiedad;
    private javax.swing.JButton EdificarCasa;
    private javax.swing.JButton EdificarHotel;
    private javax.swing.JButton HipotecarPropiedad;
    private javax.swing.JButton Jugar;
    private javax.swing.JButton SalirCarcelDado;
    private javax.swing.JButton SalirCarcelPagando;
    private javax.swing.JButton SiguienteTurno;
    private javax.swing.JButton VenderPropiedad;
    private GUIQytetet.VistaQytetet vistaQytetet1;
    // End of variables declaration//GEN-END:variables

}
